### ISSUE TITLE
Create New Playlist  -- 500 error

### ISSUE THREAD

**Issue by bakerk7** [sparkison/m3u-editor#342]
## Describe the bug

On version 0.7.9, when tryin go create a new playlist, I receive a 500 error. 

## To Reproduce

1. Go to /playlists
2. Click on new playlist
3. See 500 error

## Expected behavior

Open the page to setup a new playlist

## Actual behavior

500 error 

## Screenshots

<img width="654" height="715" alt="Image" src="https://github.com/user-attachments/assets/e8c4978e-a6c0-4f91-96e3-447021ea9e61" />

## docker-compose.yml contents

```yaml
# docker-compose.yml contents here
```

## Container/Host Logs

```log
<!-- Insert logs here -->
```

**Comment by ROPiator** [comment]
This bug seems to be existing from from version 0.7.8 onwards (tested it and found it working in 0.7.7 and older)

**Comment by sparkison** [comment]
Resolved in latest release! https://github.com/sparkison/m3u-editor/releases/tag/0.7.10

**Comment by FishPants** [comment]
Using 0.7.10 I still experience this 500 server error when interacting with existing playlists or trying to add new.
