### ISSUE TITLE
Improve Player Support for XC API

### ISSUE THREAD

**Issue by wschwa** [sparkison/m3u-editor#368]
**Is your feature request related to a problem? Please describe.**
m3u-editor hasn't been working with the IMPlayer app when using m3u-editor's XC API. I determined that it's because instead of requesting streams as "/live/user/pass/stream," IMPlayer is requesting them as "/user/pass/stream."

**Describe the solution you'd like**
Add an additional route to provide streams that omits the "/live." Something like the following in web.php:
```
Route::get('/{username}/{password}/{streamId}', [App\Http\Controllers\XtreamStreamController::class, 'handleLive'])
    ->name('xtream.stream.live.simple')
    ->where('streamId', '[0-9]+'); 
```

**Describe alternatives you've considered**
I contacted the dev of IMPlayer for support in troubleshooting, but they told me my SSL was bad (it's not), and wouldn't troubleshoot further.

**Additional context**
I added the route I suggested above into a local copy of your 0.7.11 code and built the container. It's working as expected in IMPlayer.

**Comment by sparkison** [comment]
Done! In the latest `dev` and `experimental` branches 😉 https://github.com/sparkison/m3u-editor/commit/7f495b0329a6c728ce7ccc46176b1748de0c996f

**Comment by wschwa** [comment]
Amazing work as always. Thank you!

**Comment by SortaSong** [comment]
Hello,
I tried the "Latest", "Dev" and "Experimental" Docker image and I still can't get it to work in imPlayer or OTT Navigator. Works in the M3U Iptv App.
