### ISSUE TITLE
Snappier IPTV Player TvOS

### ISSUE THREAD

**Issue by Skylinejay187** [sparkison/m3u-editor#524]
Hello I've since learned about Snappier IPTV player & it's outstanding for the fact that it can use stremio addons to load IPTV subscription movie & TV shows with premium Debrid links! However just like implayer something seems to be an issue , it takes the playlist then after closing the app it disappears it would not show live tv channels or it will disappear the movies etc , it's definitely a compatibility issue like how IMplayer wouldn't play movies , can this please be looked into? It's definitely the most advanced IPTV player out there a true all in one I hate for it to never work properly, I did test my regular IPTV subscription default login and it works perfectly no issues including a m3u from channels DVR for Verizon channels work on Snappier but once I load anything from my m3u editor playlist it will take it then start removing the channels one it's own leaving it with only one reason why is because of a possible issue with how m3u editor loads the playlist for live channels & movies! Btw when also the m3u editor playlist is loaded I do notice snappier gets really sluggish but when loading my default providers xtream code login it works flawlessly, it's definitely not a limitation of my server because implayer works perfectly fine and even better after you fixed implayers compatibility issue!

Really hope this can be resolved 

https://snappieriptv.app/

**Comment by sparkison** [comment]
This was fixed in a recent push to `dev` 😉

**Comment by Skylinejay187** [comment]
> This was fixed in a recent push to `dev` 😉

Thank you I will check it out

**Comment by Skylinejay187** [comment]
> This was fixed in a recent push to `dev` 😉

Thanks again , it seems live tv is still an issue once I added more channels & manually updated the channels went away and it was there for a while till the playlist updated , movies & shows are still there

**Comment by Skylinejay187** [comment]
When deleting the playlist from the snappier player then adding it back it then works again , but when pressing update live tv section on default playlist from provider the channels stay so not sure what it is completely but it's working just concerning for when restoring from iCloud an another apple tv but still in all I appreciate the effort!
