### ISSUE TITLE
Playlist broken on Tivimate

### ISSUE THREAD

**Issue by johnodon** [sparkison/m3u-editor#528]
I only started seeing this behavior this morning.  Tivimate on both Firestick and Chromecast are unable to read the playlist (v0.8.15-DEV).  The same playlist on IMPlayer works fine.  I'm not sure if it is related to the recent update that separated Live, VOD and Series, but I get the following message:

"Failed to update the playlists.  Make sure the playlists are properly formatted and check you Interntent connection."

Tivimate was working fine yesterday.  This happens when trying to update the existing playlist or add the playlist.

Is there anything I can provide to help troubleshoot?

TIA

**Comment by sparkison** [comment]
I think I know what it is, I've rolled back a recent change to include the username in the proxy URL. It seems like players don't like this so I've rolled back that change until I can come up with a better solution – the fix is tagged with version `0.8.16-dev`

**Comment by johnodon** [comment]
Still broken.  I actually deleted the playlist and tried to re-add it and get the same error.

**Comment by sparkison** [comment]
> Still broken. I actually deleted the playlist and tried to re-add it and get the same error.

Dang, ok, re-opened. I'll debug some more and see if I can find anything off...

**Comment by sparkison** [comment]
Just pushed a couple fixes that should resolve this. I've tested in TiviMate, Chillio and Snappier and all players were able to load and play 😉

**Comment by johnodon** [comment]
I’ll test now.  Stay tuned.,,

**Comment by johnodon** [comment]
Still broken for me, but I think I solved part of the mystery. If I add a playlist using the M3U URL, it adds fine (without VOD or series).  Trying to use the extreme API it fails.  However, while the M3 U Maps all the channels, I am not able to watch any and get error in Tivimate.

![Image](https://github.com/user-attachments/assets/c33ad08a-9b0f-4f3d-936e-0a0ade40f486)

**Comment by sparkison** [comment]
hmm, I'm not able to reproduce? It works just fine in TiviMate for me using Xtream API (screens below).
The exception you're seeing `HttpDataSource$HttpDataSourceException` looks like your ISP might be blocking you. Does the same stream work in something like VLC to test quickly?

![Image](https://github.com/user-attachments/assets/2753d1c9-e130-480a-a53f-b7e5c5cd7270)

![Image](https://github.com/user-attachments/assets/44a0d0fa-1868-4719-889f-64863a969272)

![Image](https://github.com/user-attachments/assets/cd846a70-6df6-4d51-8223-ae355d19d08f)

**Comment by johnodon** [comment]
I think teh http error was only because I tried to add the playlist via M3U which I never do so I could have done something wrong.  Anyway, I use a VPN and the only apps that go through the tunnel are Tivimate and IMPlayer.  Everything else is alloed to pass.  I've never had an issue streaming content with either player.

So, I just created a new playlist ("test") and left everything default other than the Xtream creds and server URL.  I set it to sync only Live and enabled only one group of channels:

<img width="1266" height="409" alt="Image" src="https://github.com/user-attachments/assets/97e25aea-eeae-4b07-b4ff-02dabc0ca9a0" />

When I try to add this playlist to Tivimate using the local Xtream API creds, I still get the error:

<img width="1308" height="503" alt="Image" src="https://github.com/user-attachments/assets/420049e0-3a06-4c1d-b0fc-a0aee88c1bbd" />

![Image](https://github.com/user-attachments/assets/f672bb5f-64f3-445b-ad12-105d46d559ce)

I don't know what is going on.  Adding the same playlist to IMPlayer works fine.  The only thing I can think of is that Tivimate is having issues reaching the container.  I am going to try and flip ir from Bridge to BR0 so I can get it its own IP on my network.

**Comment by johnodon** [comment]
>  I am going to try and flip ir from Bridge to BR0 so I can get it its own IP on my network.

That didn't help.  Is there a way to roll back to a previous DEV version (i.e. 0.8.13)?

**Comment by johnodon** [comment]
don't know if it helps, but here is a snippet from the 'test' playlist I spun up...

<img width="1517" height="152" alt="Image" src="https://github.com/user-attachments/assets/5d7075d4-bb20-4104-b8a7-13f86765d5b9" />

**Comment by sparkison** [comment]
> don't know if it helps, but here is a snippet from the 'test' playlist I spun up...
> 
> <img alt="Image" width="1517" height="152" src="https://private-user-images.githubusercontent.com/10155674/525962513-5d7075d4-bb20-4104-b8a7-13f86765d5b9.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU1NjYxODgsIm5iZiI6MTc2NTU2NTg4OCwicGF0aCI6Ii8xMDE1NTY3NC81MjU5NjI1MTMtNWQ3MDc1ZDQtYmIyMC00MTA0LWI4YTctMTNmODY3NjVkNWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjEyVDE4NTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZDQ2NTU1ZjRhNmFmYzI0NTIwODk0N2NlOTg3Y2VmZGVmZDA1ZWQ4NTE3YTgwYjhiNDAwNjU2YTI3ZjMzMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bvkpk-YWsxkkddNuEwGFZb_MVyjR45Yqm330ioUGy4g">

ah! Ok, I think I might know what's going on, this is helpful 😉 ...I'll follow up shortly once I have something to test...

**Comment by sparkison** [comment]
Ok, just pushed a release out! Can you try to update the container to the latest `dev` release and then try to sync the playlist again? The relative URLs should be resolved now.

**Comment by sparkison** [comment]
@johnodon, look for version `0.8.18-dev`, that should fix it up! I've confirmed with a few others having similar issues 😉

**Comment by johnodon** [comment]
Updating container now.  When done I will force a sync and then try to add to Tivimate again.

**Comment by johnodon** [comment]
This house is clean!  :)

<img width="320" height="180" alt="Image" src="https://github.com/user-attachments/assets/628cd983-cd11-465b-9381-508ad1b87e2b" />

Thank you for your attention on this!
