### ISSUE TITLE
Issue with IPTV Smarters and external facing URL

### ISSUE THREAD

**Issue by adamsdavis572** [sparkison/m3u-editor#576]
## Describe the bug

Im using a setup with AIO container, configured to act as a proxy, and a Traefik reverse proxy to expose a the service on an external URL. This works well with Tivimate on GoogleTV but i also use IPTV Smarters on Android when i'm on the go.  With Smarters no live streams or VOD work at all. The xtream actions download the playlists correctly but no request hits the m3u-editor url. 

I then tested again, connecting directly to the container, and this does work correctly. 

Working on IPTV Smarters 

{"num":89,"name":"Dirtvision 07:","stream_type":"live","stream_id":137565,"stream_icon":"http://10.10.10.11:36400/logo-proxy/aHR0cDovL3hwbGF0aW5tZWRpYS5jb206ODA4MC9pbWFnZXMvYWVmMTRhZDVhZTM3Y2Y1NmYwZGNjMTYxZjA4Y2Y5NGUucG5n","epg_channel_id":"","added":"1765808764","category_id":"751","category_ids":[751],"tv_archive":0,"tv_archive_duration":0,"custom_sid":"","thumbnail":"","direct_source":"http://10.10.10.11:36400/live/user/password/137565.ts"}

Failing on IPTV Smarters 

{"num":89,"name":"Dirtvision 07:","stream_type":"live","stream_id":137565,"stream_icon":"https://m3u-editor.my-url.net/logo-proxy/aHR0cDovL3hwbGF0aW5tZWRpYS5jb206ODA4MC9pbWFnZXMvYWVmMTRhZDVhZTM3Y2Y1NmYwZGNjMTYxZjA4Y2Y5NGUucG5n","epg_channel_id":"","added":"1765808764","category_id":"751","category_ids":[751],"tv_archive":0,"tv_archive_duration":0,"custom_sid":"","thumbnail":"","direct_source":"https://m3u-editor.my-url.net/live/user/password/138206.ts"}

so this url works "http://10.10.10.11:36400" however this does not "https://m3u-editor.my-url.net"

i have obfuscated the url but the host name is the same as the one failing and the second part also has a dash in it ie the url that is failing has 2 dashes in it. Im not sure if this is causing an issue or needs to be escaped? 

Another observation - when connecting to my provider directly "direct_source" is not populated at all its just an empty string and this works fine in the IPTV clients. would it be possible to add configuration to disable population of this field as i have a suspicion that this might fix the issue with IPTV Smarters. 

I understand this might be an issue with how IPTV Smarters handles urls or direct_source but any help you can provide would be greatly appreciated, as this works for all IPTV provider when connecting directly to there servers. 

Thanks again, and great project 👍

**Comment by sparkison** [comment]
fix pushed! Can you test the latest `dev` (or `experimental`) branch updates and confirm? I've opted to just return an empty string for `direct_source` since that's what all the providers I've tested do 😉

**Comment by adamsdavis572** [comment]
Thanks very much for looking at this. Unfortunately it still isnt working - same issue. i have looked at the server info details returned and i see a few differences here that might have an effect if the client is using them. 

Direct
{"user_info":{"username":"username","password":"password","message":"","auth":1,"status":"Active","exp_date":"1796851855","is_trial":"0","active_cons":"0","created_at":"1764970361","max_connections":"1","allowed_output_formats":["m3u8","ts"]},"server_info":{"url":"a.direct.url","port":"80","https_port":"443","server_protocol":"http","rtmp_port":"8001","timezone":"Europe\/London","timestamp_now":1767039743,"time_now":"2025-12-29 20:22:23","process":true}}


m3u-editor
{"user_info":{"username":"username","password":"password","message":"Welcome to m3u editor Xtream API","auth":1,"status":"Active","exp_date":"1796851855","is_trial":"0","active_cons":"0","created_at":"1761335704","max_connections":"1","allowed_output_formats":["ts"]},"server_info":{"xui":false,"version":null,"revision":null,"url":"https:\/\/m3u-editor.my-url.net","port":"","https_port":"","server_protocol":"https","rtmp_port":"","server_software":"m3u editor Xtream API","timestamp_now":1767039690,"time_now":"2025-12-29 20:21:30","timezone":"Europe\/London"}}




Field | Direct | m3u-editor | Notes
-- | -- | -- | --
url | ✓ | ✓(contains protocol as well) |
port | ✓ ("80") | ✓ (Empty) | Masked by editor
https_port | ✓ ("443") | ✓ (Empty) | Masked by editor
server_protocol | ✓ ("http") | ✓ ("https") | Editor forces SSL/TLS
rtmp_port | ✓ ("8001") | ✓ (Empty) | Masked by editor
timezone | ✓ | ✓ |  
timestamp_now | ✓ | ✓ |  
time_now | ✓ | ✓ |  
process | ✓ | X | Field missing in editor output
xui | X | ✓ | Editor specific field
version | X | ✓ | Editor specific field
revision | X | ✓ | Editor specific field
server_software | X | ✓ | Editor identifies itself

**Comment by sparkison** [comment]
great observations! I think I might have it now 🤞 updates applied and pushed to `dev` to test, things should more closely line up now 😉 

---

**Notes**

- the `server_protocol` will always use whatever the editor URL uses. Since yours is in the format: https://m3u-editor.my-url.net, it will always be `https`. When clients connect to: http://10.10.10.11:36400 though it will be `http`. Just a heads up there as it will automatically reflect the protocol of the editor
- since we don't currently support RTMP the `rtmp_port` value was always an empty string, I've just updated to return the default `8001` as a placeholder though just to see if it helps at all

**Comment by adamsdavis572** [comment]
thanks for this! still not working though :-( but looking much better ...

{"user_info":{"username":"username","password":"password","message":"","auth":1,"status":"Active","exp_date":"1796851855","is_trial":"0","active_cons":"0","created_at":"1761335704","max_connections":"1","allowed_output_formats":["ts"]},"server_info":{"url":"m3u-editor.my-url.net","port":"80","https_port":"80","server_protocol":"https","rtmp_port":"8001","timestamp_now":1767045961,"time_now":"2025-12-29 22:06:01","timezone":"Europe\/London","process":true}}


i think https_port needs to return 443?

**Comment by sparkison** [comment]
dang, thought it would have gotten that automatically. Updated and pushed 😉

**Comment by adamsdavis572** [comment]
Yep that's fixed it - great work! Tested and working in both https and http urls. Really appreciate the quick resolution :-)

**Comment by sparkison** [comment]
> Yep that's fixed it - great work! Tested and working in both https and http urls. Really appreciate the quick resolution :-)

awesome! Glad that fixed it, thanks for the help troubleshooting! Closing this one down 😉
