### ISSUE TITLE
Issue with m3u-editor/nginx error when starting without m3u-proxy running

### ISSUE THREAD

**Issue by donchi40** [sparkison/m3u-editor#584]
@sparkison 

[m3.txt](https://github.com/user-attachments/files/24358037/m3.txt)
So, I'm set up on the dev release
One yaml file for both m3u-editor and m3u-proxy
REDIS_ENABLED=true  # so embedded
ENABLE_POSTGRES=true # so embedded
M3U_PROXY_ENABLED=false # external

I'm having a start up issue if I try to start both containers, m3u-proxy starts up and then m3u-editor start almost the same time.
Since proxy can't talk to the editor/redis yet (it hasn't started), then I get this error:

2025-12-27 17:32:34,673 - api - INFO - m3u proxy starting up...
2025-12-27 17:32:34,673 - events - INFO - Event manager started
2025-12-27 17:32:34,674 - pooled_stream_manager - WARNING - Failed to connect to Redis: Error 111 connecting to 10.0.0.10:6379. Connection refused.. Running in single-worker mode

-------------------
If I try and start the m3u-editor by itself first, I get this in the logs:

2025-12-27 18:06:38,163 INFO success: websocket entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2025-12-27 18:06:38,163 INFO success: queue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
nginx: [emerg] host not found in upstream "m3u-proxy" in /etc/nginx/conf.d/laravel.conf:51
2025-12-27 18:06:38,185 WARN exited: nginx (exit status 1; not expected)
2025-12-27 18:06:40,188 INFO spawned: 'nginx' with pid 130
nginx: [emerg] host not found in upstream "m3u-proxy" in /etc/nginx/conf.d/laravel.conf:51
2025-12-27 18:06:40,206 WARN exited: nginx (exit status 1; not expected)
2025-12-27 18:06:43,211 INFO spawned: 'nginx' with pid 131
nginx: [emerg] host not found in upstream "m3u-proxy" in /etc/nginx/conf.d/laravel.conf:51
2025-12-27 18:06:43,234 WARN exited: nginx (exit status 1; not expected)
2025-12-27 18:06:44,235 INFO gave up: nginx entered FATAL state, too many start retries too quickly

**Comment by sparkison** [comment]
Potential fix pushed to `dev`! See here for example compose: https://github.com/sparkison/m3u-editor/blob/dev/docker-compose.embedded-redis.yml

**Comment by donchi40** [comment]
OK, good news and bad news...  I stopped and then edited the yaml file to reflect your changes...
On startup, m3u-editor start first, with no issues.
Then m3u-proxy started (since the depends_on m3u-editor was added) and again, no errors.
So that's the good news...
The bad news is none of my streams are playing via the built in player... They start and spin and spin... then I get the Failed to load stream error...  this is in the proxy log:
```INFO:     10.89.3.128:58160 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:58162 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:58178 - "GET /streams/by-metadata?field=id&value=2&active_only=1 HTTP/1.1" 200 OK
2025-12-28 09:11:37,578 - api - INFO - Using custom profile template: -fflags +genpts+discardcorrupt+igndts -i {input_ur...
2025-12-28 09:11:37,578 - stream_manager - INFO - Created new stream: e28b453a3b111a3e3cd46b065e317002 (Transcoding) with user agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
INFO:     10.89.3.128:58182 - "POST /transcode HTTP/1.1" 200 OK
2025-12-28 09:11:37,578 - api - INFO - Event: EventType.STREAM_STARTED for stream e28b453a3b111a3e3cd46b065e317002 at 2025-12-28 19:11:37.578735
INFO:     10.89.3.128:53242 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:53250 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:43304 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41294 - "GET /health?api_token=eda073a41924655819b86c853e5936e807aa411a31c75dc5 HTTP/1.1" 200 OK
INFO:     10.89.3.128:43318 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:36268 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:36274 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:60134 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
INFO:     10.89.3.128:60138 - "GET /streams/by-metadata?field=playlist_uuid&value=a081b494-1ea7-4eef-ba31-216d93a3caa0&active_only=1 HTTP/1.1" 200 OK
2025-12-28 09:12:19,826 - stream_manager - INFO - Marking stream e28b453a3b111a3e3cd46b065e317002 for cleanup: no_active_clients=True, time_diff=42.247898s, timeout=15s
2025-12-28 09:12:19,826 - stream_manager - INFO - Cleaning up inactive stream: e28b453a3b111a3e3cd46b065e317002
2025-12-28 09:12:19,826 - api - INFO - Event: EventType.STREAM_STOPPED for stream e28b453a3b111a3e3cd46b065e317002 at 2025-12-28 19:12:19.826786```

I realize it may be my proxy settings but there are some many to look at and I don't know how they keep track of each other... 
First there is the Settings, Proxy - In-app player transcoding settings.
Then there is a proxy setting for each playlist added.
Then when you edit each playlist, there is an Output tab that has a Streaming Output... 

Note: the in-app was working before but I was getting the error of the proxy couldn't connect to the editor...
Please don't get me wrong, I'm not complaining, I'm just trying to find the best order or sequence to get the in-app playing right.

**Comment by donchi40** [comment]
I went back thru he faq on the in app player is not working and checked the steps again, even went as far as to process the playlist again... but the in-app player is still not working... it tries and then it stops and I get the error...
And as I said, the in-app player was working prior to the latest dev pull...

**Comment by sparkison** [comment]
> I went back thru he faq on the in app player is not working and checked the steps again, even went as far as to process the playlist again... but the in-app player is still not working... it tries and then it stops and I get the error... And as I said, the in-app player was working prior to the latest dev pull...

If you view the browser console, do you see any errors, or is the in app player attempting to load invalid URLs? It has pretty verbose output, so if you open the browser console and attempt to play you should see a lot of output there.

For the confusion around the different transcoding profiles. The **Settings > Proxy** profiles are for the in-app player _only_. They will be used for the in-app player when no Playlist transcoding profiles are set (**Playlist > Edit > Output**). If a Playlist has transcoding profile is set, they will take priority.

**Comment by donchi40** [comment]
OK, getting somewhere on this... so I just tried 2 different channels (in 2 different custom playlists) and both are showing Bad Gateway...
Not sure what this means because if I paste the links for those 2 custom playlists in VLC, the same channels play...
So this means my container's network connection out is not working?

<img width="401" height="413" alt="Image" src="https://github.com/user-attachments/assets/c7fdb458-0462-49bb-80e6-83be1f2cdafc" />


I shelled into the editor and I can ping and curl www.google.com.
I shelled into the proxy and ping is not there, but curl www.google.com works...
From the proxy, I can successfully curl 10.0.0.10:36400

**Comment by sparkison** [comment]
if you access http://10.0.0.10:36400/m3u-proxy/docs do you see the docs? Or get an error?

**Comment by donchi40** [comment]
It spins for a long time and then I get the error

<img width="211" height="76" alt="Image" src="https://github.com/user-attachments/assets/c2b8e7da-68bd-46a8-9b6f-9e4e376b8916" />

**Comment by sparkison** [comment]
> It spins for a long time and then I get the error

got it! So the internal proxy route is failing. If you go to **Settings > Proxy** and press the _Test m3u proxy connection_ button, does it return? Or show an error?

**Comment by donchi40** [comment]
It connects successfully...

<img width="257" height="251" alt="Image" src="https://github.com/user-attachments/assets/7da1c422-2db8-4e55-8b56-8c6199d45fa8" />

Not sure if it matters but I'm on the latest dev v0.8.25-dev

**Comment by sparkison** [comment]
> It connects successfully...
> 
> Not sure if it matters but I'm on the latest dev v0.8.25-dev

hmm, ok, so the internal connection is working. That's good at least! Can you post your compose file? You can replace sensitive info, just looking for structure and what variables are set.

**Comment by donchi40** [comment]
I have a couple of additions based on working this with Fink... so I know it may need some cleanup...


```services:
  m3u-editor:
    image: sparkison/m3u-editor:dev
    container_name: m3u-editor
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Honolulu
      - APP_URL=${APP_URL:-http://localhost}
      - APP_PORT=${APP_PORT:-36400}
      - ENABLE_POSTGRES=true
      - PG_DATABASE=${PG_DATABASE:-m3ue}
      - PG_USER=${PG_USER:-m3ue}
      - PG_PASSWORD=${PG_PASSWORD:-changeme}
      - PG_PORT=${PG_PORT:-5432}
      - DB_CONNECTION=pgsql
      - DB_HOST=localhost
      - DB_PORT=${PG_PORT:-5432}
      - DB_DATABASE=${PG_DATABASE:-m3ue}
      - DB_USERNAME=${PG_USER:-m3ue}
      - DB_PASSWORD=${PG_PASSWORD:-changeme}
      - REDIS_ENABLED=true
      - REDIS_PORT=6379
      - REDIS_SERVER_PORT=6379
      - REDIS_PASSWORD=${M3U_PROXY_TOKEN:-changeme}
      - M3U_PROXY_ENABLED=false
      - M3U_PROXY_PORT=${M3U_PROXY_PORT:-38085}
      - M3U_PROXY_HOST=${M3U_PROXY_HOST:-m3u-proxy}
      - M3U_PROXY_TOKEN=${M3U_PROXY_TOKEN:-changeme}
    volumes:
      - ./data:/var/www/config
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - ${APP_PORT:-36400}:${APP_PORT:-36400}
    networks:
      - iptv_default
    dns:
      - 1.1.1.1
    healthcheck:
      test: curl -f http://localhost:36400/up
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s
  m3u-proxy:
    image: sparkison/m3u-proxy:dev
    container_name: m3u-proxy
    environment:
      - TZ=Pacific/Honolulu
      - API_TOKEN=${M3U_PROXY_TOKEN:-changeme}
      - M3U_PROXY_TOKEN=${M3U_PROXY_TOKEN:-changeme}
      - PORT=${M3U_PROXY_PORT:-38085}
      - REDIS_ENABLED=true
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_SERVER_PORT=6379
      - REDIS_HOST=${REDIS_HOST:-m3u-editor}
      - REDIS_PASSWORD=${M3U_PROXY_TOKEN:-changeme}
      - REDIS_DB=6
      - ENABLE_REDIS_POOLING=true
      - LOG_LEVEL=INFO
      - PUBLIC_URL=${M3U_PROXY_PUBLIC_URL:-http://localhost:36400/m3u-proxy}
    restart: unless-stopped
    networks:
      - iptv_default
    dns:
      - 1.1.1.1
    depends_on:
      m3u-editor:
        condition: service_healthy
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: curl -f
        http://127.0.0.1:${PROXY_PORT:-38085}/health?api_token=${M3U_PROXY_TOKEN:-changeme}
      interval: 60s
      timeout: 2s
      retries: 12
      start_period: 10s
networks:
  iptv_default:
    external: true```

**Comment by sparkison** [comment]
I'm not seeing anything obvious anyway. The `PUBLIC_URL` is deprecated and no longer used, otherwise I'd say it's that. Are you using Caddy or some other reverse proxy in front of this setup to use a custom domain name?

**Comment by donchi40** [comment]
No, I'm not using any other service live Caddy or reverse proxy.
I'm going to remove that PUBLIC_URL line and restart it...

OK, removed the line and started up again.
Proxy test works...
Streams still giving the 502 Bad Gateway, so no go...

**Comment by donchi40** [comment]
Thanks for trying to assist on this... I'm going to close this issue... 
I'm just going to delete this container and start fresh...

**Comment by donchi40** [comment]
OK, stopped the container, deleted all the associated files.
Made a new container and put the embedded redis yaml file with a few modifications for my site, pulling in the dev image on both.
Started up the containers, m3u-editor started and built the database, after it was healthy, m3u-proxy started and got healthy.
Went in and added a playlist and it's epg and then map them.
Went into Stream Profiles and Generated Default Profiles.
Went to Settings, Proxy.  Added the Default Live Profile to the in-app player.
Saved the settings.  
Click the Test m3u proxy connection button, got the Connection Successful, no red seen.
Click the m3u proxy API docs button, new tab opens, spins for a while and then got the dreaded nginx/1.26.3 -  502 Bad Gateway error.

Tried to load the latest (not dev) m3u-editor image, but it wouldn't start, seeing I'm using a different yaml file...
Killed the whole thing again, and this time, used the old yaml with the external proxy and redis, but the dev image...
Started it up and let it pull the appropriate images... but it would not start properly as it kept bombing trying to access editor first...

So, deleted it all again and put back the latest dev, and the internal redis yaml file... 
So, I hate to say this but it's back in your court when you have the time... 
I can use what I have, I just can't use the in-app player...

**Comment by donchi40** [comment]
@sparkison Sorry to do this to you... I'm going to close this out again, as I got what I needed to work... 
What I did was blow everything away and then used the AIO compose file...along with the "latest" image pull...
No errors on start up... 
Proxy checks out, the API Docs works now.
Added a playlist and epg... Success... I'm able to play the stream with the in-app player.
Shut it down and changed to the dev image...
Started it up, and again everything I needed works...
I'm good for now, over the next few days, I'm going to see if I really miss anything about what's in the other compose files, the external proxy, etc.  
Again, sorry for the headaches, and again, appreciation for the work done so far.
Final note: only thing I see that may be a concern is the Hardware Acceleration shows the red X and Disabled but at this time, I don't see any issues with the streams... will gauge it over the next few days.
